version: pythonocc-core-0.16.3-dev.{build}

environment:
  matrix:
    - PYTHON: "C:\\Python27_32"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "32"
      CONDA_PY: "27"
      CONDA_NPY: "18"
      generator: "MSYS Makefiles"
      Compiler: MinGW-gcc-4.8.1
      ARCH: "Win32"
    - PYTHON: "C:\\Python27_32"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "32"
      CONDA_PY: "27"
      CONDA_NPY: "18"
      generator: "Visual Studio 14"
      ARCH: "Win32"
      Compiler: "MSVC2015"
    - PYTHON: "C:\\Python27_64"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "64"
      CONDA_PY: "27"
      CONDA_NPY: "18"
      generator: "MSYS Makefiles"
      ARCH: "Win64"
      Compiler: MinGW64-gcc-5.2.0

    - PYTHON: "C:\\Python34_32"
      PYTHON_VERSION: "3.4"
      PYTHON_ARCH: "32"
      CONDA_PY: "34"
      CONDA_NPY: "18"
      generator: "MSYS Makefiles"
      ARCH: "Win32"
      Compiler: MinGW64-gcc-5.2.0

    - PYTHON: "C:\\Python34_64"
      PYTHON_VERSION: "3.4"
      PYTHON_ARCH: "64"
      CONDA_PY: "34"
      CONDA_NPY: "18"
      generator: "MSYS Makefiles"
      ARCH: "Win32"
      Compiler: MinGW64-gcc-5.2.0

cache:
  - i686-4.9.3-release-posix-dwarf-rt_v4-rev1.7z
  - x86_64-5.2.0-release-posix-seh-rt_v4-rev0.7z

configuration:
  #- Debug
  - Release

branches:
  only:
    - master
    - /^review/

shallow_clone: true 

# scripts that run after cloning repository
install:
  # this installs the appropriate Miniconda (Py2/Py3, 32/64 bit),
  # as well as pip, conda-build, and the binstar CLI
  - powershell .\\ci\\appveyor\\appveyor_install_conda.ps1
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # download/install OCE from DLR-SC channel
  - conda install -c https://conda.anaconda.org/dlr-sc oce
  # download/install swig
  - conda install --yes -c https://conda.anaconda.org/salilab swig

build_script:
  - cmd: if "%generator%" == "MSYS Makefiles" (C:\MinGW\msys\1.0\bin\sh --login /c/projects/pythonocc-core/ci/appveyor/make-pythonocc-core-msys.sh)
      else (CALL C:\projects\pythonocc-core\ci\appveyor\make-pythonocc-core-msvc.bat)
