version: pythonocc-core-0.16.3-dev.{build}

environment:
  env:
  matrix:
    - python_version: "2.7"
      CONDA_PY: "27"
    - python_version: "3.5m"
      CONDA_PY: "35"

# scripts that run after cloning repository
install:
  # this installs the appropriate Miniconda (Py2/Py3, 32/64 bit),
  # as well as pip, conda-build, and the binstar CLI
  - powershell .\\ci\\appveyor\\appveyor_install_conda.ps1
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
   # download/install OCE from DLR-SC channel
  - conda config --add channels https://conda.anaconda.org/dlr-sc
  # install everything required to build the receipe
  - conda install conda-build anaconda-client

script:
  - conda build ci/conda

branches:
  only:
    - master
    - /^review/
